import * as Yup from 'yup';

import {
  TOO_SHORT_EXCEPTION_TEXT,
  TOO_LONG_EXCEPTION_TEXT,
  SPECIAL_CHARACTER_EXCEPTION_TEXT,
  NUMERIC_DIGIT_EXCEPTION_TEXT,
  LOWER_CASE_LETTER_EXCEPTION_TEXT,
  UPPER_CASE_LETTER_EXCEPTION_TEXT,
  CONFIRM_PASSWORD_EXCEPTION_TEXT,
  INVALID_EMAIL_EXCEPTION_TEXT,
  REQUIRED_EXCEPTION_TEXT
} from 'shared/constants';

export const EMAIL_FORM_SCHEMA = {
  email: Yup.string()
    .email(INVALID_EMAIL_EXCEPTION_TEXT)
    .required(REQUIRED_EXCEPTION_TEXT)
};

export const PASSWORD_FORM_SCHEMA = {
  password: Yup.string()
    .min(8, TOO_SHORT_EXCEPTION_TEXT)
    .max(20, TOO_LONG_EXCEPTION_TEXT)
    .matches(/^(?=.*[@$!%*#?&])/, SPECIAL_CHARACTER_EXCEPTION_TEXT)
    .matches(/^(?=.*\d)/, NUMERIC_DIGIT_EXCEPTION_TEXT)
    .matches(/^(?=.*[a-z])/, LOWER_CASE_LETTER_EXCEPTION_TEXT)
    .matches(/^(?=.*[A-Z])/, UPPER_CASE_LETTER_EXCEPTION_TEXT)
    .required(REQUIRED_EXCEPTION_TEXT)
};

export const CONFIRM_PASSWORD_FORM_SCHEMA = {
  ...PASSWORD_FORM_SCHEMA,
  confirmPassword: Yup.string()
    .oneOf([Yup.ref('password')], CONFIRM_PASSWORD_EXCEPTION_TEXT)
    .required(REQUIRED_EXCEPTION_TEXT)
};
